apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: bsrapp-backend
  ports:
    - protocol: TCP
      name: backend
      port: 8000
      targetPort: 8000
      nodePort: 30800